name: build

on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' || matrix.experimental }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [
          2.7,
          3.0
        ]
        gemfile: [
          "gemfiles/Gemfile.rails-5.2.x",
          "gemfiles/Gemfile.rails-6.1.x",
          "gemfiles/Gemfile.rails-7.0.x"
        ]
        experimental: [false]
        exclude:
          - ruby: "3.0"
            gemfile: gemfiles/Gemfile.rails-5.2.x

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/bundle
          key: bundle-use-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.ruby }}-${{ matrix.gemfile }}-gems-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle install
        run: |
          gem install bundler -v 2.1.4
          bundle config path /home/runner/bundle
          bundle config --global gemfile ${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3

      - name: RSpec
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: bundle exec rspec
          debug: true
